import { NextRequest, NextResponse } from "next/server";

export const runtime = "edge";

// SHA-256 hash of Google's default globe favicon (726 bytes, same across all sizes)
// Generated by fetching: google.com/s2/favicons?domain=<nonexistent>.invalid&sz=64
const GOOGLE_GLOBE_SHA256 =
  "59bfe9bc385ad69f50793ce4a53397316d7a875a7148a63c16df9b674c6cda64";
const GOOGLE_GLOBE_SIZE = 726;

function arrayBufferToHex(buffer: ArrayBuffer): string {
  return Array.from(new Uint8Array(buffer))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

function domainToColor(domain: string): string {
  let hash = 0;
  for (let i = 0; i < domain.length; i++) {
    hash = domain.charCodeAt(i) + ((hash << 5) - hash);
  }
  const hue = Math.abs(hash % 360);
  return `hsl(${hue}, 40%, 55%)`;
}

function generateLetterSvg(domain: string): string {
  const letter = domain.replace(/^www\./, "").charAt(0).toUpperCase();
  const color = domainToColor(domain);
  return `<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64">
  <rect width="64" height="64" rx="12" fill="${color}"/>
  <text x="32" y="32" dy=".1em" fill="white" font-family="-apple-system,BlinkMacSystemFont,system-ui,sans-serif" font-size="32" font-weight="600" text-anchor="middle" dominant-baseline="central">${letter}</text>
</svg>`;
}

async function isGlobeIcon(body: ArrayBuffer): Promise<boolean> {
  if (body.byteLength !== GOOGLE_GLOBE_SIZE) return false;
  const hashBuffer = await crypto.subtle.digest("SHA-256", body);
  return arrayBufferToHex(hashBuffer) === GOOGLE_GLOBE_SHA256;
}

const CACHE_HEADERS = {
  // 30 days on Vercel CDN, 1 day in browser, 7 days stale-while-revalidate
  "Cache-Control":
    "public, s-maxage=2592000, max-age=86400, stale-while-revalidate=604800",
};

export async function GET(request: NextRequest) {
  const domain = request.nextUrl.searchParams.get("domain");
  if (!domain) {
    return new NextResponse("Missing domain parameter", { status: 400 });
  }

  if (!/^[a-zA-Z0-9._-]+$/.test(domain) || domain.length > 253) {
    return new NextResponse("Invalid domain", { status: 400 });
  }

  // 1. Try DuckDuckGo first (returns proper 404 for missing favicons)
  try {
    const res = await fetch(
      `https://icons.duckduckgo.com/ip3/${domain}.ico`,
      { signal: AbortSignal.timeout(3000) },
    );
    if (res.ok) {
      const contentType = res.headers.get("content-type");
      if (contentType?.startsWith("image/")) {
        const body = await res.arrayBuffer();
        return new NextResponse(body, {
          headers: { "Content-Type": contentType, ...CACHE_HEADERS },
        });
      }
    }
  } catch {
    // DDG timeout or network error — fall through to Google
  }

  // 2. Try Google Favicon API (detect and reject default globe icon)
  try {
    const res = await fetch(
      `https://www.google.com/s2/favicons?domain=${encodeURIComponent(domain)}&sz=64`,
      { signal: AbortSignal.timeout(3000) },
    );
    if (res.ok) {
      const body = await res.arrayBuffer();
      if (!(await isGlobeIcon(body))) {
        const contentType = res.headers.get("content-type") || "image/png";
        return new NextResponse(body, {
          headers: { "Content-Type": contentType, ...CACHE_HEADERS },
        });
      }
    }
  } catch {
    // Google timeout or network error — fall through to letter
  }

  // 3. Generate letter SVG fallback
  const svg = generateLetterSvg(domain);
  return new NextResponse(svg, {
    headers: { "Content-Type": "image/svg+xml", ...CACHE_HEADERS },
  });
}
