import type { Metadata } from 'next';
import { HomeContent } from "@/components/features/home-content";
import { setRequestLocale } from 'next-intl/server';
import { routing } from '@/i18n/routing';
import { generateAlternates } from '@/lib/seo/alternates';

// Force static generation for this page
export const dynamic = 'force-static';

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

// Metadata for the homepage
// Note: OG images are generated by opengraph-image.tsx and twitter-image.tsx
// using Next.js file-based metadata convention for proper caching and reliability
export const metadata: Metadata = {
  title: 'Bypass Paywalls & Read Full Articles Free - No Login | Smry',
  description: 'Paste any paywalled article link and get the full text plus an AI summary. Free to use, no account, no browser extension. Works on most major news sites.',
  alternates: generateAlternates('/'),
  openGraph: {
    title: 'Bypass Paywalls & Read Full Articles Free | Smry',
    description: 'Paste any paywalled article link and get the full text plus an AI summary. Free to use, no account required.',
    url: 'https://smry.ai',
    // Images handled by opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Bypass Paywalls & Read Full Articles Free | Smry',
    description: 'Paste any paywalled article link and get the full text plus an AI summary. Free to use, no account required.',
    // Images handled by twitter-image.tsx
  },
};

type Props = {
  params: Promise<{ locale: string }>;
};

export default async function Home({ params }: Props) {
  const { locale } = await params;
  setRequestLocale(locale);

  return <HomeContent />;
}
