/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as ProxyRouteImport } from './app/proxy'
import { Route as PricingRouteImport } from './app/pricing'
import { Route as HistoryRouteImport } from './app/history'
import { Route as HardPaywallsRouteImport } from './app/hard-paywalls'
import { Route as AdminRouteImport } from './app/admin'
import { Route as LocaleRouteImport } from './app/$locale'
import { Route as SplatRouteImport } from './app/$'
import { Route as IndexRouteImport } from './app/index'
import { Route as LocaleIndexRouteImport } from './app/$locale/index'
import { Route as ApiSplatRouteImport } from './app/api.$'
import { Route as LocaleProxyRouteImport } from './app/$locale/proxy'
import { Route as LocalePricingRouteImport } from './app/$locale/pricing'
import { Route as LocaleHistoryRouteImport } from './app/$locale/history'
import { Route as LocaleHardPaywallsRouteImport } from './app/$locale/hard-paywalls'
import { Route as LocaleSplatRouteImport } from './app/$locale/$'

const ProxyRoute = ProxyRouteImport.update({
  id: '/proxy',
  path: '/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HardPaywallsRoute = HardPaywallsRouteImport.update({
  id: '/hard-paywalls',
  path: '/hard-paywalls',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleProxyRoute = LocaleProxyRouteImport.update({
  id: '/proxy',
  path: '/proxy',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePricingRoute = LocalePricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleHistoryRoute = LocaleHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleHardPaywallsRoute = LocaleHardPaywallsRouteImport.update({
  id: '/hard-paywalls',
  path: '/hard-paywalls',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSplatRoute = LocaleSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/admin': typeof AdminRoute
  '/hard-paywalls': typeof HardPaywallsRoute
  '/history': typeof HistoryRoute
  '/pricing': typeof PricingRoute
  '/proxy': typeof ProxyRoute
  '/$locale/$': typeof LocaleSplatRoute
  '/$locale/hard-paywalls': typeof LocaleHardPaywallsRoute
  '/$locale/history': typeof LocaleHistoryRoute
  '/$locale/pricing': typeof LocalePricingRoute
  '/$locale/proxy': typeof LocaleProxyRoute
  '/api/$': typeof ApiSplatRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/hard-paywalls': typeof HardPaywallsRoute
  '/history': typeof HistoryRoute
  '/pricing': typeof PricingRoute
  '/proxy': typeof ProxyRoute
  '/$locale/$': typeof LocaleSplatRoute
  '/$locale/hard-paywalls': typeof LocaleHardPaywallsRoute
  '/$locale/history': typeof LocaleHistoryRoute
  '/$locale/pricing': typeof LocalePricingRoute
  '/$locale/proxy': typeof LocaleProxyRoute
  '/api/$': typeof ApiSplatRoute
  '/$locale': typeof LocaleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/admin': typeof AdminRoute
  '/hard-paywalls': typeof HardPaywallsRoute
  '/history': typeof HistoryRoute
  '/pricing': typeof PricingRoute
  '/proxy': typeof ProxyRoute
  '/$locale/$': typeof LocaleSplatRoute
  '/$locale/hard-paywalls': typeof LocaleHardPaywallsRoute
  '/$locale/history': typeof LocaleHistoryRoute
  '/$locale/pricing': typeof LocalePricingRoute
  '/$locale/proxy': typeof LocaleProxyRoute
  '/api/$': typeof ApiSplatRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/$locale'
    | '/admin'
    | '/hard-paywalls'
    | '/history'
    | '/pricing'
    | '/proxy'
    | '/$locale/$'
    | '/$locale/hard-paywalls'
    | '/$locale/history'
    | '/$locale/pricing'
    | '/$locale/proxy'
    | '/api/$'
    | '/$locale/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/admin'
    | '/hard-paywalls'
    | '/history'
    | '/pricing'
    | '/proxy'
    | '/$locale/$'
    | '/$locale/hard-paywalls'
    | '/$locale/history'
    | '/$locale/pricing'
    | '/$locale/proxy'
    | '/api/$'
    | '/$locale'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/$locale'
    | '/admin'
    | '/hard-paywalls'
    | '/history'
    | '/pricing'
    | '/proxy'
    | '/$locale/$'
    | '/$locale/hard-paywalls'
    | '/$locale/history'
    | '/$locale/pricing'
    | '/$locale/proxy'
    | '/api/$'
    | '/$locale/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  AdminRoute: typeof AdminRoute
  HardPaywallsRoute: typeof HardPaywallsRoute
  HistoryRoute: typeof HistoryRoute
  PricingRoute: typeof PricingRoute
  ProxyRoute: typeof ProxyRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/proxy': {
      id: '/proxy'
      path: '/proxy'
      fullPath: '/proxy'
      preLoaderRoute: typeof ProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hard-paywalls': {
      id: '/hard-paywalls'
      path: '/hard-paywalls'
      fullPath: '/hard-paywalls'
      preLoaderRoute: typeof HardPaywallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/proxy': {
      id: '/$locale/proxy'
      path: '/proxy'
      fullPath: '/$locale/proxy'
      preLoaderRoute: typeof LocaleProxyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/pricing': {
      id: '/$locale/pricing'
      path: '/pricing'
      fullPath: '/$locale/pricing'
      preLoaderRoute: typeof LocalePricingRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/history': {
      id: '/$locale/history'
      path: '/history'
      fullPath: '/$locale/history'
      preLoaderRoute: typeof LocaleHistoryRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/hard-paywalls': {
      id: '/$locale/hard-paywalls'
      path: '/hard-paywalls'
      fullPath: '/$locale/hard-paywalls'
      preLoaderRoute: typeof LocaleHardPaywallsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/$': {
      id: '/$locale/$'
      path: '/$'
      fullPath: '/$locale/$'
      preLoaderRoute: typeof LocaleSplatRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleSplatRoute: typeof LocaleSplatRoute
  LocaleHardPaywallsRoute: typeof LocaleHardPaywallsRoute
  LocaleHistoryRoute: typeof LocaleHistoryRoute
  LocalePricingRoute: typeof LocalePricingRoute
  LocaleProxyRoute: typeof LocaleProxyRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleSplatRoute: LocaleSplatRoute,
  LocaleHardPaywallsRoute: LocaleHardPaywallsRoute,
  LocaleHistoryRoute: LocaleHistoryRoute,
  LocalePricingRoute: LocalePricingRoute,
  LocaleProxyRoute: LocaleProxyRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  LocaleRoute: LocaleRouteWithChildren,
  AdminRoute: AdminRoute,
  HardPaywallsRoute: HardPaywallsRoute,
  HistoryRoute: HistoryRoute,
  PricingRoute: PricingRoute,
  ProxyRoute: ProxyRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
